services:
  frontend:
  mysql:
    image: mysql:8
    # restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: survey_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/my.cnf:/etc/mysql/my.cnf
